### ISSUE TITLE
현재 재고 상황 확인 기능 요청

### ISSUE THREAD

**Issue by AzelyFox** [MoonJuhan/PandoracubeAccountingBot#1]
KakaoTalk Bot 이용 현재 재고 상황 확인 기능 Request

**Comment by MoonJuhan** [comment]
구글 스프레드 시트 DB의 데이터를 JSON으로 받아오는 기능 조사 완료
조만간 작업 예정입니다 ^^ 1.3 업데이트를 기다려 주세요
