### ISSUE TITLE
현재 자신의 결제/주문 이력 확인 기능

### ISSUE THREAD

**Issue by AzelyFox** [MoonJuhan/PandoracubeAccountingBot#2]
KakaoTalk Bot 이용 현재 주문 상황 확인 기능 Request

**Comment by MoonJuhan** [comment]
구글 스프레드 시트 DB의 데이터를 JSON으로 받아오는 기능 조사 완료
조만간 작업 예정입니다 ^^ 1.3 업데이트를 기다려 주세요

**Comment by MoonJuhan** [comment]
v1.3의 기능중 하나로 추가되었습니다
관심 가져주셔서 감사합니다 ㅎㅎ
